### ISSUE TITLE
README.md Correction ng-lo.rom SHA1

### ISSUE THREAD

**Issue by 2play** [libretro/neocd_libretro#11]
I think the correct SHA1 for ng-lo.rom shoudl be 5992277DEBADEB64D1C1C64B0A92D9293EAF7E4A

**Comment by RomainQuidet** [comment]
mine is as readme defines. It's working.

**Comment by fabrice-martinez** [comment]
It is possible now to use the (recent) MAME version of this file.
(See README.md)

**Comment by 2play** [comment]
@fabrice-martinez 
yes i use the latest with no problem
