### ISSUE TITLE
Mame CHD support fails to compile on macOS

### ISSUE THREAD

**Issue by RomainQuidet** [libretro/neocd_libretro#15]
Seems that the original C sources is not correctly followed and missing a flag.
PR #14

**Comment by fabrice-martinez** [comment]
LzFintMt.c is Windows specific and will prevent compilation under Linux as well.
I thought I had removed this already, looks like I messed up when merging changes.
I'll merge your patch, thank you :)

**Comment by RomainQuidet** [comment]
Merci à toi !! Superbe projet, ça me donne envi de reprendre mon dev neogeo ;)
