### ISSUE TITLE
No .wav support on Linux? "Could not open WAVE file: xxx File was not found or had incorrect format."

### ISSUE THREAD

**Issue by bslenul** [libretro/neocd_libretro#2]
Hey!

First, awesome work on that core, it's working very well and the "Skip CD Loading" option is sooo good! <3

I tried with the game Ironclad on Windows 10, no problem the game and musics work fine. However I compiled the core for my Linux VM (following the instructions you provided on this github main page) but it fails when loading the .wav files:

```
[libretro ERROR] Could not open WAVE file: /home/bobby/Desktop/ironclad/02.wav
File was not found or had incorrect format.
[ERROR] Failed to load content.
```
(I simplified the filenames just to make sure it wasnt a path/characters issue, and modified the .cue file to reflect this change)
If I remove every .wav lines from the .cue it loads and plays fine but, of course, without musics.

Converting the .wav files in .ogg works.
**edit:** Works fine with .flac too!

It just doesnt seem to like .wav on Linux for some reason 🤔 Or maybe I'm just missing something, I'm not a big Linux user :p

**Comment by fabrice-martinez** [comment]
Wave files should work on Linux, so definitely a bug.
I'd say probably some structure alignment issue.
Thanks for the report!

**Comment by fabrice-martinez** [comment]
Turns out the problem was completely different from what I had expected.
A name conflict in macros defined in endian.h.
I simply changed the name of my macros.
Just git pull and recompile, should work now.

**Comment by bslenul** [comment]
Yup, just confirming it is now working perfectly fine with .wav files.

Thanks a lot for the fix! Keep up the good work 👍
