### ISSUE TITLE
CHD broken?

### ISSUE THREAD

**Issue by darksaviorx** [libretro/neocd_libretro#20]
I haven't compiled a new version since like June. The binary I compiled back then still works with CHD on my pi3/4 but I wanted to compile a new version. None of my CHD's work with this new binary. They all load to the neocd menu screen. No "press start". No game logo. I can see the track listing but it won't play any tracks. It loaded an IMG\CUE fine.

**Comment by fabrice-martinez** [comment]
Works fine under Windows.
I'll test on Raspi later.

**Comment by Darknior** [comment]
Works perfectly for me too on my PI3b+ with last Batocera 5.24 Beta and last Retroarch.

**Comment by darksaviorx** [comment]
> Works perfectly for me too on my PI3b+ with last Batocera 5.24 Beta and last Retroarch.

I'm not sure I'm compiling correctly. I'm using
 "set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -march=native ${BASE_OPTIONS} ${CXX_OPTIONS}")"
CHD doesn't work on retropie using a pi3b+ and a pi4b.

**Comment by kikexx** [comment]
Please, can you release an actual compiled build with chd support fotr windows?

**Comment by fabrice-martinez** [comment]
The emulator is going to be added to RetroArch's buildbot pretty soon meaning there will be pre-compiled packages for the supported platforms

**Comment by srk15372** [comment]
great new, hope it will work on android shied tv
regards

**Comment by Sanaki** [comment]
This issue should be resolved at this point. The buildbot is building it fine and most of us have no issues with chd files.

**Comment by darksaviorx** [comment]
Yes, I can confirm the issue is gone with the libretro nightly builds.
