### ISSUE TITLE
Metal Slug 2 Turbo Pause menu goes too fast

### ISSUE THREAD

**Issue by ghost** [libretro/neocd_libretro#23]
Now I don't know if it's just this particular hack or what, but whenever I load up Metal Slug 2 with the Turbo hack, if I pause, notably in combat school, the menu freaks out and I can't really pick anything even in slowdown mode.

https://streamable.com/ca0wr

**Comment by LesserDescension** [comment]
This is the nature of the hack itself. If you play the AES version of Metal Slug 2 with the hack and access the [debug menu](http://randomhoohaas.flyingomelette.com/msmia/debug.html) the same thing happens—it's too fast to do anything.
