### ISSUE TITLE
Universe 3.2 does not work

### ISSUE THREAD

**Issue by ToniBC** [libretro/neocd_libretro#24]
Hi, I was testing and it turns out that MAME bios work all but Universe 3.2 (uni-bioscd.rom).

When you use that bios, it loads the menu but does not detect any disk image, either in CHD or bin / cue.

The other three bios do load without problems, Front Loader BIOS (MAME), Top Loader BIOS (MAME) and CDZ BIOS (MAME).

It would be interesting to look at that, because usually Unibios usually adds some extras to the games.

Thank you.

**Comment by Darknior** [comment]
I use it from some month and it works perfectly, i can load my games with unibios cd.
It's the best bios, so bad it not include cheat like on ROM games.

**Comment by ghost** [comment]
I'm getting this issue too, it worked with the previous version if I swapped one of the other bios for Unibios via renaming, but now it won't detect anything if I load it via Uni, my files are in Bin/Cue format and are detected fine if I use any other bios, but not Unibios.

**Comment by fabrice-martinez** [comment]
Hi, this is because the Universe Bios is recognized as a CDZ bios. (Which it is really)
You need to press SELECT in the CD player and choose CDZ in the menu that opens.
You need to do this only once (settings are saved to memory card)

**Comment by Darknior** [comment]
Yes it is @fabrice-martinez  ... sorry i dont think to explain this, i've understand it alone.
Only the first time and it's rock
