### ISSUE TITLE
Build failures - Linux

### ISSUE THREAD

**Issue by inactive123** [libretro/neocd_libretro#25]
@fabrice-martinez 

The last time it tried to compile on our buildbot, we got these errors - 

http://paste.libretro.com/169575

**Comment by inactive123** [comment]
BTW, would you like to visit us on Discord? It's not a requirement but it'd be nice if it's possible. You can find the link on retroarch.com - Socials / Discord. we could perhaps more easily talk about development that way.

**Comment by gouchi** [comment]
It has been fixed since [latest commit](https://github.com/libretro/neocd_libretro/commit/5016cf5802f75820c7bec0e47224785b4177a2d2).
