### ISSUE TITLE
android port please~

### ISSUE THREAD

**Issue by duskgao** [libretro/neocd_libretro#3]
How about port the core to android retroarch?

**Comment by fabrice-martinez** [comment]
I have zero experience in Android development so it won't happen anytime soon, sorry.

**Comment by duskgao** [comment]
> I have zero experience in Android development so it won't happen anytime soon, sorry.

Never mind,if you merge your code in libretro mainstream,maybe someone would port it. Thanks for your work. There is no standalone ngcd emulator for android for a long time. We can wait it ...

**Comment by srk15372** [comment]
I hope for an android port too on shield tv  thanks

**Comment by srk15372** [comment]
hi, any news to port your marvelous core on the buildbot for android version ? Thanks again

**Comment by srk15372** [comment]
Hi is there any way to have a neocd core for android compiled on the buildbot ?  thanks

**Comment by Immersion95** [comment]
Hi, thanks a lot for this core.

I saw that a libnx build is in the way, is that true ? If yes, would it be possible to port it to Android as both are ARM devices ?

Thanks a lot !

**Comment by gouchi** [comment]
Should be fixed with #30. Now it needs to be added to buildbot.

**Comment by gouchi** [comment]
Please report if it is working correctly as it has been [added to the buildbot](https://github.com/libretro/libretro-super/commit/05f1d6841b710909bcfe274327ea571f561f0bf5#diff-c30296f7d48038210ccecd5303d6d150R67).

**Comment by Immersion95** [comment]
Thanks a lot for your work !

Will test this evening.

**Comment by gouchi** [comment]
Thanks to @jdgleaver !

**Comment by srk15372** [comment]
thank you so much for this android version  works on shield tv even with run ahead.
have to test chd support.
thanks again

**Comment by Immersion95** [comment]
Works flawlessly, CHD tested. THX :)

**Comment by gouchi** [comment]
Great news !

@duskgao @fabrice-martinez this issue can be closed now ;-)
