### ISSUE TITLE
[Feature Request] Achievement support

### ISSUE THREAD

**Issue by Sanaki** [libretro/neocd_libretro#32]
Tried adding it to RALibretro just to see and memory currently isn't exposed. I'd like to see the ability to use this core with RetroAchievements one day, if at all reasonable.

**Comment by fabrice-martinez** [comment]
I suppose it means implementing memory maps for the core, I can look into that.

**Comment by Darknior** [comment]
Excellent idea :)

**Comment by fabrice-martinez** [comment]
Just pushed a version that exposes memory, let me know if it works.

**Comment by Sanaki** [comment]
Looks like it does, now it seems it's on RALibretro's end. To quote Jamiras on the topic:
> The problem with the map is that we have to map our addresses to the exposed addresses, which is a per-console thing. when we just fetch RETRO_MEMORY_SYSTEM_RAM, it's assumed to be one contiguous block starting at our address $0000
> the memory map acts like a system bus. it indicates "real" addresses and which bits of the address redirect to which pieces of memory

**Comment by Sanaki** [comment]
Given that the core end of this appears to be resolved, I'm closing this issue.
