### ISSUE TITLE
Permission to add NeoCD to Steam as free DLC for RetroArch

### ISSUE THREAD

**Issue by inactive123** [libretro/neocd_libretro#33]
Hi @fabrice-martinez,

We would like to seek your permission to include NeoCD as a core as free DLC for RetroArch on Steam.

The user would have to manually install this, it would be freely made available.

If there's anything you are unsure of or are hesitant about, don't hesitate to bring it to our attention. We will always go with whatever you decide.

**Comment by fabrice-martinez** [comment]
Sure, no problem. The core is already being distributed by you guys in the non steam version, it's no different :)

**Comment by inactive123** [comment]
Thank you.

**Comment by inactive123** [comment]
Good news - we are now on Steam!

https://store.steampowered.com/app/1227456/RetroArch__NeoCD/

**Comment by fabrice-martinez** [comment]
Yay! Cool logo :)
