### ISSUE TITLE
Re-enabled OGG support

### ISSUE THREAD

**Issue by figolu31** [libretro/neocd_libretro#36]
Hello,
since chd support, the OGG support don't work in pi3. CHD files run very well, iso+wav or flac also.
It's possible to re-enable this ?
Thanks for all your work,

**Comment by fabrice-martinez** [comment]
Works fine under Windows. I'll have to check on RPi... Unfortunately won't be able to at least before the end of next week

**Comment by fabrice-martinez** [comment]
Although I have not tested it on RPi, OGG support should work now.
