### ISSUE TITLE
Games not loading with Per Game Saves and Universe Bios enabled.

### ISSUE THREAD

**Issue by ghost** [libretro/neocd_libretro#38]
Whenever I load up any game (tested with both Metal Slugs, Twinkle Star Sprites, King of Fighters 98, and Super Spy), if I load it up with Per Games saves on alone, it works fine, if I load that up while using the Universe Bios then it won't load the game, it just loads the boot screen.

**Comment by fabrice-martinez** [comment]
So I just tested with Twinkle Star Sprites and loading works with Universe Bios 3.2. Strangely it looks like the BIOS don't remember the CDZ setting. It's supposed to.

**Comment by ghost** [comment]
> 
> 
> So I just tested with Twinkle Star Sprites and loading works with Universe Bios 3.2. Strangely it looks like the BIOS don't remember the CDZ setting. It's supposed to.

Was that with per game saves enabled? Unibios on my end works fine, if I have both options enabled then it only loads up the main boot screen, not the game.

**Comment by ghost** [comment]
Just tested a few more times with different settings applied on and off, still the same results. If I only have Per game settings on it'll work fine, and if I only have Universe Bios enabled it'll work fine, but if I have them both enabled then it won't load past the main dashboard screen, none of the other settings made a difference when I tested it out. Using different ISO sets didn't make a difference either (Tested with both TOSEC and Redump)

**Comment by ghost** [comment]
Found a fix, you have to open the Unibios menu within the game and set the loader/region to your core region (If you set it to USA/Top Loader in Retroarch, set it to that ingame via Unibios), then the game got detected and loads even with per game saves on.
