### ISSUE TITLE
Any chance of support for Universe Bios 3.3?

### ISSUE THREAD

**Issue by ghost** [libretro/neocd_libretro#39]
The creator of the Unibios recently released the latest version for free (for both CD and the regular NEO GEO)

http://unibios.free.fr/

Any chance of seeing it supported in NeoCD?

**Comment by fabrice-martinez** [comment]
Sure it will be supported. Just need check what changed between the versions.

**Comment by Sanaki** [comment]
Took a look, doesn't seem any actual changelog exists, all I can see is "All issues affecting v3.2 should be fixed."

**Comment by ghost** [comment]
> 
> 
> Took a look, doesn't seem any actual changelog exists, all I can see is "All issues affecting v3.2 should be fixed."

I think one of the issues fixed involved Metal Slug 2 Turbo, using cheats in that version of the games caused a reboot before, but now that's fixed with this version.

**Comment by Darknior** [comment]
Yes some interesting fix, can be really cool tu use it with this great emulator :)

**Comment by d4NY0H** [comment]
Thumbs up for supporting Unibios 3.3. That would be awesome.

**Comment by fabrice-martinez** [comment]
Work in progress, this is coming soon.

**Comment by AlanRibas** [comment]
could someone tell me how important this unibios is? Is it an official bios or created by someone?

and speaking of bios of neogeo CD ... the bios shown in this photo below I could not find. Can anyone give me any tips? Are they important for any specific game?

<img width="960" alt="A" src="https://user-images.githubusercontent.com/16063712/85185481-7eb09280-b26a-11ea-8a9e-689636a08959.png">

**Comment by ToniBC** [comment]
When I select the uni-bios, it does not load the iso, that is, if I put the bios "top-sp1" the CD menu comes out and with the number of tracks, etc ... you press Start and everything is correct.

With uni-bios it loads the menu, but it doesn't detect the iso and of course, it doesn't work.

All this with the MAME games on CHD.

**Comment by Sanaki** [comment]
I can confirm the same behavior with both 3.2 and 3.3 (for anyone unaware, it detects your bios by contents rather than by name now). Other bioses, such as SMKDAN (final releases, not matching the hashes shown on the readme) and MAME's three work fine.

Tested using Crossed Swords 2, Redump verified, in chd format.

**Comment by ghost** [comment]
> When I select the uni-bios, it does not load the iso, that is, if I put the bios "top-sp1" the CD menu comes out and with the number of tracks, etc ... you press Start and everything is correct.
> 
> With uni-bios it loads the menu, but it doesn't detect the iso and of course, it doesn't work.
> 
> All this with the MAME games on CHD.

I had that before, it only SNK on the menu right?

Check you settings in quick menu (specifically region), then in the actual ngcd menu, bring up the Unibios me u (I forget the exact button combo but it's a set of the four face buttons), that allows changing region. Change it to USA if you have it set, and if the bios doesn't say CDZ them change that too, should work from there.

**Comment by fabrice-martinez** [comment]
Uni 3.3 supported now

**Comment by Sanaki** [comment]
I can confirm that if internally configured to CDZ (select button on CD player), it'll start CDZ-only games (ADK World). That said, when configured to front loader, it currently does not start games that appear incompatible with CDZ (Metal Slug, Choutetsu Brikin'ger ~ Ironclad - Tesshou Rusha). ~~This may be resolved by whatever the fix would be for #60 would be.~~

EDIT: As of fc85ed4 those games work in CDZ mode, but still not front-loader.
