### ISSUE TITLE
Raspberry Pi 3 Binary?

### ISSUE THREAD

**Issue by darksaviorx** [libretro/neocd_libretro#4]
For noobs that can't compile like me, thanks.

**Comment by fabrice-martinez** [comment]
This is possible but I'll have to check if an annoying bug in Raspbian has been fixed first.
This is the reason I switched to Arch Linux long ago.

**Comment by darksaviorx** [comment]
With some help from a user on the retropie forum, and actually trying to compile, it wasn't so bad. 
I tested a bunch of games and most of them seem to run well...except for Samurai Shodown 3. 
The game freezes the pi completely a few seconds after the match starts every time. 

I used:
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -march=armv8-a+crc -mtune=cortex-a53 ${BASE_CXX_OPTIONS}")

but I also tried the -march=native option with the same results.

**Comment by fabrice-martinez** [comment]
I've finally gotten around to update my Raspberry Pi and indeed Samsho3 freezes as you described.
I'm going to look into that.

Thanks for the report.

**Comment by fabrice-martinez** [comment]
It's tied to the speed hacks that I had implemented so low power platforms like Raspberry Pi can load faster. Apparently some very specific conditions can send the emulator into an infinite loop.
If you disable speed hacks in the options menu the problem go away.

Still investigating...

**Comment by fabrice-martinez** [comment]
Looks like I spoke too soon... It just happens randomly....

**Comment by fabrice-martinez** [comment]
It was the HIRQ timer callback entering an infinite loop.
Just git pull and recompile, should work.

Fixed in 4ea30f8d18bddda129acea18cff77e27362a416c
