### ISSUE TITLE
Playstation Vita port

### ISSUE THREAD

**Issue by kwyxz** [libretro/neocd_libretro#40]
A PS Vita port of this emulator would be phenomenal : storage space is expensive on the Vita, and being able to use CHDs is definitely a killer feature, along with load times skip!

**Comment by gouchi** [comment]
Please make some test as it is now available on buildbot.

Thanks to @phcoder !

**Comment by kwyxz** [comment]
As discussed on Discord #bounties there still are performance issues with several titles, but technically the port is done and it's running!
