### ISSUE TITLE
FBAlpha developper seeking help

### ISSUE THREAD

**Issue by barbudreadmon** [libretro/neocd_libretro#5]
We are encountering an issue in the ngcd implementation of FBAlpha, and i thought you might be able to share a few tips : "The Last Blade 2" is rebooting and going back to the cd player screen at the end of the loading screen. @dinkc64 has been trying to fix this issue (and apparently the game never worked in MAME either) but is about to give up, any idea what could be causing this ? I think that's pretty much the only game still unplayable in FBAlpha, and it's working in your emulator.

Also, it might be useful to show you the files involved with ngcd in FBAlpha : 
https://github.com/libretro/fbalpha/blob/master/src/burner/libretro/retro_cdemu.cpp => iso reading
https://github.com/libretro/fbalpha/blob/master/src/burn/drv/neogeo/neo_run.cpp => machine emulation

**Comment by barbudreadmon** [comment]
Finally sorted out this issue :), thanks anyway !

**Comment by fabrice-martinez** [comment]
Hi, sorry I'm late.

I had this problem too and it was because of interrupts.
If I recall correctly it was because the interrupt priorities from the CD-ROM decoder (0x54) and CD-ROM communications (0x58) were reversed.

Glad you guys sorted the issue :)

**Comment by barbudreadmon** [comment]
No problem for the late reply :)

I'm not too sure about the details but yeah, it seems it was an issue with irqs.
