### ISSUE TITLE
Current (non-beta) SMKDAN bioses are not detected and patched/labeled

### ISSUE THREAD

**Issue by Sanaki** [libretro/neocd_libretro#56]
With the new auto-detection of bioses, most bioses are labeled correctly, including universe bioses with labels such as `(CDZ, Universe 3.3)`. SMKDAN bioses on the other hand just show as `(Top Loader)` and `(CDZ)`, which requires the user rename them to attempt to distinguish them. It would be preferable if the auto-detection labeled SMKDAN bioses correctly, in a similar fashion to Universe's labels.

**Comment by Sanaki** [comment]
Having looked into this myself a little, it seems there are indeed supported SMKDAN bioses which are available on the SMKDAN website still, but are not linked to publicly. These ones are named with an extra B in the name (`007B_F`, `007B_T`, and `007BZ`, presumably indicating beta) and are from five months after the ones actually linked to on the website (`007T` and `007Z`). Regardless, it would help to have the easily accessible versions handled by the core. I'm going to attempt to see if I can implement this myself, but I'm honestly not sure I have the requisite knowledge to do so correctly.

EDIT: Yeah, it was a bit beyond my knowledge of the system.

**Comment by inactive123** [comment]
Hi @fabrice-martinez , it looks like they need this for RetroAchievements integration to work.

**Comment by fabrice-martinez** [comment]
http://smkdan.eludevisibility.org/ngcd/BIOS007.zip
is all I have.
No 007B_F, 007B_T or 007BZ in there :(

**Comment by Sanaki** [comment]
The beta versions are already handled, and are available here:
https://smkdan.eludevisibility.org/ngcd2/

So far as I can tell, that isn't actually linked anywhere on the site. The issue is that the ones easily accessed by users visiting the site directly, the ones you just linked, are not handled as SMKDAN bioses by the core.

In case it's of interest, other bioses available from the site but not listed (all older), sorted by timestamp:
https://smkdan.eludevisibility.org/ngcd/cd.zip
https://smkdan.eludevisibility.org/ngcd/neocdalt.zip
https://smkdan.eludevisibility.org/ngcd/neocdmenu.zip
https://smkdan.eludevisibility.org/ngcd/neocdfronttest.zip
https://smkdan.eludevisibility.org/ngcd/neocdtest.zip
https://smkdan.eludevisibility.org/ngcd/neocdstart.zip
https://smkdan.eludevisibility.org/ngcd/neocdfixes.zip
https://smkdan.eludevisibility.org/ngcd/BIOS003.zip
https://smkdan.eludevisibility.org/ngcd/BIOS004.zip
https://smkdan.eludevisibility.org/ngcd/BIOS004A.zip
https://smkdan.eludevisibility.org/ngcd/BIOS004B.zip
https://smkdan.eludevisibility.org/ngcd/BIOS005.zip
https://smkdan.eludevisibility.org/ngcd/may3.zip
https://smkdan.eludevisibility.org/ngcd/006Z.zip
https://smkdan.eludevisibility.org/ngcd/pulstar.zip

Optimally, even if the bios patching isn't available for them all (I'd imagine that'd be a bit much work for little if any gain), it'd be nice if they could be identified as SMKDAN, both for troubleshooting purposes and for our purposes at RetroAchievements. But the only real -critical- ones are the easily obtainable ones.

**Comment by fabrice-martinez** [comment]
Should be fixed with 1b04b0bcb974d350787b5d5344c16a23a4b5fc16.

Thanks for the links, I will look at the rest later :)

**Comment by Sanaki** [comment]
Looks good. Thanks for that. For the others, while categorizing everything perfectly is always a nice goal, you might just consider tossing an "Unknown" label on anything that misses the other identifiers and thus isn't getting bios patches applied. Up to you though.
