### ISSUE TITLE
W10 retroarch crash when launch a game with neocd core

### ISSUE THREAD

**Issue by jhdgghost** [libretro/neocd_libretro#57]
Hello,

I am trying to run some games with retroarch in W10 and everytime i launch a game cue or chd retorarch crash. Rest of cors work perfectly. I am using a new Acer Nitro5 with GTX1650. The games are good it run with fbneo and the same games run with the neocd core in m rpi4.

I run retroarch with logging 

[INFO] [CONTENT LOAD]: Updating firmware status for: C:\RetroArch-Win64\cores\neocd_libretro.dll on C:\RetroArch-Win64\system
[INFO] [CORE]: Using content: E:\retropie-mount\roms\neocd\Last Blade 2.chd.
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.
[INFO] RetroArch 1.9.1 (Git 2951391)
[INFO] === Build =======================================
[INFO] CPU Model Name: AMD Ryzen 5 4600H with Radeon Graphics         
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Apr  6 2021
[INFO] Version: 1.9.1
[INFO] Git: 2951391
[INFO] =================================================
[INFO] [Input]: Found input driver: "dinput".
[INFO] [Core]: Loading dynamic libretro core from: "C:\RetroArch-Win64\cores\neocd_libretro.dll"
[INFO] [Overrides]: No core-specific overrides found at "C:\RetroArch-Win64\config\NeoCD\NeoCD.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "C:\RetroArch-Win64\config\NeoCD\neocd.cfg".
[INFO] [Overrides]: No game-specific overrides found at "C:\RetroArch-Win64\config\NeoCD\Last Blade 2.cfg".
[INFO] [Remaps]: Remap directory: "C:\RetroArch-Win64\config\remaps".
[INFO] [Overrides]: Redirecting save file to "C:\RetroArch-Win64\saves\Last Blade 2.srm".
[INFO] [Overrides]: Redirecting save state to "C:\RetroArch-Win64\states\Last Blade 2.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SYSTEM_DIRECTORY: "C:\RetroArch-Win64\system".
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[INFO] Core requested VFS version >= v1, providing v3
[libretro INFO] Using front end provided VFS routines

I have the bios in neocd in system folder I use the same bios in rpi4 and the core works perfectly.

Some possible explanation?? In retroarch i indicated the debug level for retroarch and core but the log file not seem very informative at least to me.

Kind Regards

**Comment by jhdgghost** [comment]
I forget to say i was using the last stable windows retroarch version and also i try last nightly from yesterday with the same results

**Comment by fabrice-martinez** [comment]
I tried with the latest stable, no crash on my end. 
The log don't indicate anything wrong.

Is your bios in an archive (zip, rar, 7z, etc...) ?

**Comment by jhdgghost** [comment]
Thanks for trying and your answer. I have files in zip and uncompress with several of the bios files. 

Later at home i will send at snapshot of my system/neocd folder if there something critical is missing and i am not detecting.

I am trying this in a new laptop, does neocd use some specific library not common to other cores. Because I install vulkan directx and other but maybe still something else. Some incompatibilty with some of the retrorarch drivers?

**Comment by jhdgghost** [comment]
![image](https://user-images.githubusercontent.com/25726039/114252324-8d3f7600-9972-11eb-986f-854b88654ff1.png)

Hello here how it looks my retroarch/system/neocd/ I check some of the checksums and are correct.

I reinstalled th retroarch with last nightly and download the core again but still nothing. For the video driver i am using vulkan.

Thank you

**Comment by fabrice-martinez** [comment]
Looks OK I would say. I mentioned zipped BIOS because I had a problem previously where neocd would crash on some of my machines and not on others. Took me a while to figure the cause was the BIOS zipped on the machine that crashed and not on others. Subtle bug in the code that handles archives, but it should be fixed now.

**Comment by jhdgghost** [comment]
Strange, I reinstall everything and update everything as yesterday was changes in the core code, but still retroarch just close when I load the game with the core.  Not seems is missing the BIOS.

The only thing occurs to me is some dependency is not there, but the log offers no info.

**Comment by fabrice-martinez** [comment]
Can you look in the Windows Event Viewer to see if it says something about retroarch crashing or missing DLLs?

**Comment by jhdgghost** [comment]
The error that appears just after i reproduce the error is

Log Name:      Microsoft-Windows-AppModel-Runtime/Admin
Source:        Microsoft-Windows-AppModel-Runtime
Date:          4/10/2021 8:29:40 AM
Event ID:      65
Task Category: None
Level:         Error
Keywords:      Process
User:          LAPTOP-OL5FP80E\jhdgg
Computer:      LAPTOP-OL5FP80E
Description:
Failed with 0x57 retrieving AppModel Runtime status for package Windows.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-AppModel-Runtime" Guid="{f1ef270a-0d32-4352-ba52-dbab41e1d859}" />
    <EventID>65</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x2000000000000001</Keywords>
    <TimeCreated SystemTime="2021-04-10T12:29:40.7253072Z" />
    <EventRecordID>4315</EventRecordID>
    <Correlation />
    <Execution ProcessID="9024" ThreadID="12484" />
    <Channel>Microsoft-Windows-AppModel-Runtime/Admin</Channel>
    <Computer>LAPTOP-OL5FP80E</Computer>
    <Security UserID="S-1-5-21-2725048107-3716698547-3047795314-1001" />
  </System>
  <EventData>
    <Data Name="ErrorCode">87</Data>
    <Data Name="PackageFullName">Windows</Data>
  </EventData>
</Event>

Seems related to graphics card. I have a GTX 1650 in my laptop updated to last drivers. But is working fine because is working with all the other cores i try and in games . Also i forced retroarch use the integrated graphics but the error is the same so not seems ralted to NVIDIA.

I make a quick search and some people fix the problems after a new update. I keep looking.

Kind Regards

**Comment by jhdgghost** [comment]
Seems the problem was fixed. With last retroarch build 23042021 and updating the core now the emulator launch with no issue and everything works.
Apart from that and keeping my pc updated with last drivers. So not sure if some of the changes in retroarch or core help but happy it works now. I close the issue. One stupid question when I load a game I see the bios animation (front loader) and after goes in the menu and after when press start load the game. Is there is a way to launch the game directly without going to the menu. Is a stupid thing but curious if there is a way

Thank you
