### ISSUE TITLE
[Suggestion] Clarification of Bios 

### ISSUE THREAD

**Issue by ghost** [libretro/neocd_libretro#59]
The documentation does not say if the bios files have to zipped or not. If zipped do they have to be placed in a particular zip file name? I've seen some zipped forms with some of them in neogeocd.zip and neogeocdz.zip

For the core lr-neocd it says to place bios in 
/home/pi/RetroPie/BIOS/neocd
With the minimum of 2 bios files (eg. ng-lo.rom, uni-bioscd.rom)

Tried that for that core and it did not work.

**Comment by fabrice-martinez** [comment]
The core looks for bios files under <system>/neocd and any sub-directory under that.
It will look for files with extension .bin and .rom, including inside .zip and .7z archives (name of the archive does not matter).
It will then load the files and look for certain signatures to identify the BIOS (a bit like what antivirus software does) details are in bios.cpp.
ng-lo.rom is not needed anymore.

**Comment by fabrice-martinez** [comment]
Support for 7z archives will be removed in the next version

**Comment by ghost** [comment]
From Lakka OS nightly build
RPi 4

Whats the deal with SMKDAN 0.7b DEC 2010 and the MAME versions of the bios? Im trying to understand whats their significance. Im I better off using all of them?

Lists the bios as optional. 
![Neo CD bios](https://user-images.githubusercontent.com/73009731/114827116-27415d00-9d7d-11eb-88d8-4d0a4577bdca.png)

**Comment by fabrice-martinez** [comment]
MAME versions are stock BIOS but different dumps.
SMKDAN is a hacked BIOS with integrated cheats, dip settings and more.

You don't have to have them all, just use your favorite BIOS :)
I would recommend a front loader BIOS as this is what I'm used to and I do all my testing on it.
