### ISSUE TITLE
Support of latest BIOS roms & CHD support

### ISSUE THREAD

**Issue by randombyt** [libretro/neocd_libretro#6]
Currently this core only supports specific BIOS roms which originated from obsolete sets, please also add support for  BIOS roms from current sets. I hope CHD support will be added too. 

Thanks for the core, results are very good in few titles I tested,

**Comment by fabrice-martinez** [comment]
Sorry for the late answer, I was on a business trip.
CHD support is planned and currently still only half implemented (via libchdr). 
I need to rewrite cdrom.cpp for chd support to be complete.
I was not aware of newer BIOS dumps, just to be sure I have looked at the latest MAME source and the hashes have not changed.

**Comment by randombyt** [comment]
NP, thanks a lot for your core. Retroarch provides so many Quality of Life additions to emulation. The roms mentioned in readme require much older romsets. For example "ng-lo.rom" (aka "000-lo.lo") with the said SHA1 value "2b1c719531dac9bb503f22644e6e4236b91e7cfc" is only available from sets older then MAME v0.127u5. The current sets don't match, it has the SHA1 value of "5992277debadeb64d1c1c64b0a92d9293eaf7e4a". Finding such old sets can be difficult as most sources only retain the latest versions of MAME.

**Comment by fabrice-martinez** [comment]
Done! (see README.md)
