### ISSUE TITLE
[Regression] CDZ bios freezes frontend with CD Speed Hack enabled for some games

### ISSUE THREAD

**Issue by Sanaki** [libretro/neocd_libretro#60]
I tested with Samurai Shodown RPG and Metal Slug, in both cases retroarch froze hard as soon as the bios intro had finished, or as soon as you hit start to bypass it. Both games start fine with front- and top-loader bioses. ADK World and Far East of Eden by contrast started fine with CDZ. I checked both bin+cue and chd, in all cases Redump-verified. Core was self-compiled on x86_64 Linux.

Since the same games that freeze with CDZ here can't actually start via FBNeo, I'm assuming they're just not compatible with the CDZ system at all. I don't expect -that- to be worked around, I'd just like a fix for the freeze.

**Comment by bslenul** [comment]
It was working previously, after bisecting it looks like the first "bad" commit is ad1a6b6ed7ed9fe425bfb1f46310254d79aa7e3f.

**Comment by Sanaki** [comment]
Looks like with the CD Speed Hack enabled and Skip CD Loading disabled, it stalls ("wait for a moment" displayed if you hit start to skip) but doesn't freeze retroarch. With CD Speed Hack disabled and Skip CD Loading enabled (or disabled), it gets into the bios properly, but still can't launch the game. With both enabled, it hard freezes retroarch.

**Comment by fabrice-martinez** [comment]
Good catch, thanks for the report :)
I think I know what is happening but first I need to finish implementing the new libchdr

**Comment by bslenul** [comment]
Seems to be fixed with fc85ed4f5e3d075945493a3ae103df53b63cb340 (only tried on Windows tho), tested with every combination of "CD Speed Hack" and "Skip CD Loading" ON/OFF 👍

**Comment by Sanaki** [comment]
Confirmed on Linux as well. Closing this issue.
