### ISSUE TITLE
Neo Drift Out: New Technology not working

### ISSUE THREAD

**Issue by ToniBC** [libretro/neocd_libretro#62]
Hello, it turns out that the game Neo Drift Out: New Technology in its CD Redump or MAME version does not work. All this tested under Windows with the updated core and Retroarch also updated to the latest nightly.

Specifically, the game loads correctly, but when you go to start a race, the car comes out and the core resets itself.

I have tried removing the speedhack and skipping loading time and the same thing happens. You cannot play because the game resets.

Thanks.

**Comment by fabrice-martinez** [comment]
Indeed. I'm pretty sure it worked at some point.
I'm going to need to find the change that breaks this game.

**Comment by fabrice-martinez** [comment]
Fixed in 323f1029254186245fb5483ea7d31a856d1eac60.
Thanks for the report :)
