### ISSUE TITLE
Tengai makyou shinden Not booting past BIOS

### ISSUE THREAD

**Issue by riggles1** [libretro/neocd_libretro#63]
Game won't boot and keeps you at the CD player BIOS with no tracks or anything you can do. Using RetroArch 1.9.4 on Windows with the latest neocd core in there.

All other games I've played work well, except for Neo Turf Masters which won't play sound effects 50% of the time.

**Comment by fabrice-martinez** [comment]
Works fine for me. Tested a CHD version as well as my own dump with Front Loader and CDZ bios.
Maybe a bad dump?

**Comment by riggles1** [comment]
Possibly, not having issues now that I try it again, after a while.
