### ISSUE TITLE
Unibios very slow in menus

### ISSUE THREAD

**Issue by tapperp** [libretro/neocd_libretro#64]
Using latest retroarch 1.9.5 and updated neocd core, with unibios 3.3 (tried 3.2 with same results).

Games run fine, unibios features work. However, on all computers I tested, the unibios menus are very, very slow. For example, when choosing unibios region and console type, it takes several seconds for a selection to be acknowledged. Another example is when entering/exiting the unibios cheats menu - when the text splits and scrolls to the sides, that graphical transition is extremely slow.

Here is a youtube video showing what I mean: https://youtu.be/OsEPnwDo2zc

One computer has a 6700K with nVidia 1080, and the other is an intel based laptop with 1060. Both are running Windows 10, fully updated etc. Same issue occurs on my GPD Win Max as well.

Oddly, the same core with unibios works perfectly on my handheld Anbernic 351V, with no slowdown in the unibios menus. My PC's are far more powerful, so I cannot understand what is causing this issue.

**Comment by fabrice-martinez** [comment]
Fixed in 323f1029254186245fb5483ea7d31a856d1eac60.
Thanks for the report :)
