### ISSUE TITLE
[PS Vita] Crash on latest retroarch

### ISSUE THREAD

**Issue by evillurker** [libretro/neocd_libretro#65]
Whenever I try to load a CHD the core crashes retroarch on the vita (Retroarch 1.9.6)
This doesn't happen on Retroarch nightly build from March 10th

**Comment by phcoder** [comment]
I tested with my PR https://github.com/libretro/neocd_libretro/pull/70 and it works other than being slow (I tested with Magician Lord and it clocks only 40 fps). So looks like it was fixed either by it or before it
