### ISSUE TITLE
Neocd Core Doesn't Have Multi Keys Button

### ISSUE THREAD

**Issue by yudhiyou** [libretro/neocd_libretro#66]
Please, can you add multi keys button on Neocd core like on FBNeo core? I meant like AB, CD, ABC, and BCD buttons.
Because those buttons are very crucial for neogeo games.
Also if you mind can you also add Fake Analog keys like on FBNeo core too? Because it is also important for playing on analog gamepad.

Thank you very much.

**Comment by fabrice-martinez** [comment]
That's a good idea, adding this to the list of things to do :)

**Comment by yudhiyou** [comment]
Thanks...

**Comment by fabrice-martinez** [comment]
It's implemented in 3aa984f8d951ed43240a97233879b7063ea808e8
