### ISSUE TITLE
New feature.

### ISSUE THREAD

**Issue by Jmi95110** [libretro/neocd_libretro#67]
Hi guys,

Could you enventually add a function to play random tracks ?
I have some "bestofs" of  kof games with multiples variations for the same stage. I would like add these musics on my games.

Thanks for reading.
Regards.

**Comment by fabrice-martinez** [comment]
I don't think many people would want that feature.
Alternatively you can create many CUE files with the same DATA track and different audio tracks.
Choose one at random when you play.
