### ISSUE TITLE
Any way for make a Nintendo Wii version of this core?

### ISSUE THREAD

**Issue by saulfabregwiivc** [libretro/neocd_libretro#73]
I see that on RetroArch Wii there's still no neocd_libretro core.

And i want to see how i can play decently NeoGeo CD games on Wii.

Is there any chance for make a Wii version of this core?

Thanks!! :)

**Comment by fabrice-martinez** [comment]
I don't have a Nintendo console at home to test but apparently it's available:
[neocd_libretro.rpx.zip](https://buildbot.libretro.com/nightly/nintendo/wiiu/latest/neocd_libretro.rpx.zip)

**Comment by saulfabregwiivc** [comment]
this is for Wii U btw :p

i'm referring to the original Wii (RVL).
