### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by fabrice-martinez** [libretro/neocd_libretro#8]
Just to remember what needs to be done.
Progress will be slow, sorry.

- Work with Autechre to integrate the core with buildbot
- Make BIOS handling more flexible:
	* Read BIOSes from zip files
	* Identify by SHA1
	* Identify by name (same as MAME)
 	* Identify by contents (and "cdz" in the name means CDZ BIOS)
 	* Patches only applied when identified by SHA1
 	* Add a way to select the reply to command 20-7 (Useful for unpatched CDZ BIOS)
- (DONE) MAME CHD support via libchdr
- Use libretro_common vfs for file I/O instead of C++ iostreams
- Use libretro_common rthreads instead of C++11 threads
- Check that C++11 regexes are usable on bare metal platforms (no OS)
- Rest of the C++11 features used in the emulator should be header only, meaning at this point it can be compiled for platform with no OS (consoles, ...)

**Comment by srk15372** [comment]
HI, I hope you will update your marvelous core soon thanks again and make it available on the buildbot

**Comment by Darknior** [comment]
> (DONE) MAME CHD support via libchdr

I'm not sure to understand ? we can convert our ISO+OGG files to CHD ?
When i read the doc i can only read you support ISO and CUE files.

> Read BIOSes from zip files

Good idea if we can do it one day :)

**Comment by Darknior** [comment]
Ok CHD are working really fine, sorry for the stupid question

**Comment by inactive123** [comment]
Hi,

adding a static Makefile for the libretro port would make porting this to other platforms AND deploying this on the buildbot much easier. It could literally be done overnight then.

You can use one of the other static Makefiles from the other cores as a reference. Just one Makefile and Makefile.common will do.

**Comment by Darknior** [comment]
Is this core support Netplay ? I can't found information no where ?
Thanks a lot

**Comment by fabrice-martinez** [comment]
As far as I know netplay is based on rewind and rewind works on NeoCD, so it should work.
Correct me if I'm wrong :)

**Comment by Darknior** [comment]
Thanks @fabrice-martinez . 
I have try it myself with all other core, to list the core with Netplay on Batocera and help users.
Internet doc and RA wiki havn't all the informations and for all the core like yours.

And NEOCD crash when we launch a game with netplay :(
Blackscreen and come back to Emulation Station.
Where a C64 core will start fine, show the IP, but the netplay will not works and the 1 player will be never assigned.
And where a SNES emu will will works fine like we can read on the doc.
NEOCD is the only one that crash. I don't know why?
If you think Netplay can works with it, please can you try to fix it ?
Thanks

**Comment by alex2005jp** [comment]
Hello, 
Does NEOCD core actually support save games through the NeoGeo CD backup memory?
Somehow I am trying it on Retroarch and by some reason I cant save the games' progress (I dont want to use save states, but the original "memory" saves of the console.
If not: is this is a feature you plan to implement at some point?
Thanks a lot!

**Comment by fabrice-martinez** [comment]
All done.
