### ISSUE TITLE
Request Force 60hz Framerate Feature

### ISSUE THREAD

**Issue by yudhiyou** [libretro/neocd_libretro#80]
Because of original neogeo framerate is below 60hz, the gameplay isn't smooth on screen.
Can you add force 60hz framerate feature on neocd? Currently this feature has been available already on fbneo.

Thank you very much.

**Comment by fabrice-martinez** [comment]
It's already implemented. 
RetroArch does this for you.

There are two cases:
- If you have a freesync capable gpu and monitor, disable vsync in RetroArch and Neocd will run at 59.19Hz like a real Neo Geo
- If you don't have freesync, enable vsync in RetroArch. Neocd will run at 60Hz and RetroArch will slightly adjust the pitch of the audio to compensate.

**Comment by yudhiyou** [comment]
Ok. Thank you very much.
