### ISSUE TITLE
[WiiU] Broken CHD Music

### ISSUE THREAD

**Issue by Ploggy** [libretro/neocd_libretro#84]
It looks like the CHD Music has always been broken in one way or another.. 
From whenever the Core was added to WiiU to the v1.9.0 stable there was no Music at all but then from v1.9.1 stable to the current version we get static sounds.

Music will play correctly if a game is loaded from Bin/Cue so its specifically CHD that's the issue :)
I have compiled the OG Wii version of the Core to check and that suffers from the same problem too, so endian issues?

Thanks :)

**Comment by rtissera** [comment]
@Ploggy can you test latest core as we bumped libchdr ?

**Comment by Ploggy** [comment]
> @Ploggy can you test latest core as we bumped libchdr ?

I just tried it again with your latest changes but the Audio is the same.

**Comment by rtissera** [comment]
Ok thanks for feedback we indeed have endian issues in dr_flac or libretro
build process.

**Comment by Ploggy** [comment]
Yea, it would be nice to have CHD Audio but at least for now we can play Audio with Bin/Cue :)

**Comment by fabrice-martinez** [comment]
Hi @rtissera it's nice to have you here.

I think I understand what is happening.

Looking into `drflac_read_pcm_frames_s16` I see no byte swapping is done. 
This means audio data is returned in **whatever endianness the host machine is**.

This is different from BIN/CUE or WAV files where audio data is **always little endian**.

In neocd, `cdrom.cpp`, there is the following in `Cdrom::readAudioDirect`:
```cpp
#ifdef BIG_ENDIAN_MACHINE
    if (m_currentTrack->trackType == CdromToc::TrackType::AudioPCM ||
	m_currentTrack->trackType == CdromToc::TrackType::AudioWav) {
        int i;
	uint16_t *buffer16 = (uint16_t *) buffer;
	for (i = 0; i < size / 2; i++) {
	  buffer16[i] = BYTE_SWAP_16(buffer16[i]);
	}
    }
#endif
```

This is fine in the case of BIN/CUE files but not CHD.
The easy fix is to leave the audio data alone when the underlying file is a CHD, like so:

```cpp
#ifdef BIG_ENDIAN_MACHINE
    if ((m_currentTrack->trackType == CdromToc::TrackType::AudioPCM ||
	m_currentTrack->trackType == CdromToc::TrackType::AudioWav)  && (!m_file->isChd())) {
        int i;
	uint16_t *buffer16 = (uint16_t *) buffer;
	for (i = 0; i < size / 2; i++) {
	  buffer16[i] = BYTE_SWAP_16(buffer16[i]);
	}
    }
#endif
```

I will look into that once I am back home.

**Comment by rtissera** [comment]
@fabrice-martinez yes, totally agree with your analysis.
Let's see if dr_flac upstream fixes the issue first.

**Comment by rtissera** [comment]
https://github.com/mackron/dr_libs/blob/master/dr_flac.h#L1818

The vendored version in this repo has the code too, it just seems to be missing some proper defines to honor the big endian nature of devices such as WiiU (I can guess other big endian platforms are affected too).

**Comment by Ploggy** [comment]
> Hi @rtissera it's nice to have you here.
> 
> I think I understand what is happening.
> 
> Looking into `drflac_read_pcm_frames_s16` I see no byte swapping is done. This means audio data is returned in **whatever endianness the host machine is**.
> 
> This is different from BIN/CUE or WAV files where audio data is **always little endian**.
> 
> In neocd, `cdrom.cpp`, there is the following in `Cdrom::readAudioDirect`:
> 
> ```c++
> #ifdef BIG_ENDIAN_MACHINE
>     if (m_currentTrack->trackType == CdromToc::TrackType::AudioPCM ||
> 	m_currentTrack->trackType == CdromToc::TrackType::AudioWav) {
>         int i;
> 	uint16_t *buffer16 = (uint16_t *) buffer;
> 	for (i = 0; i < size / 2; i++) {
> 	  buffer16[i] = BYTE_SWAP_16(buffer16[i]);
> 	}
>     }
> #endif
> ```
> 
> This is fine in the case of BIN/CUE files but not CHD. The easy fix is to leave the audio data alone when the underlying file is a CHD, like so:
> 
> ```c++
> #ifdef BIG_ENDIAN_MACHINE
>     if ((m_currentTrack->trackType == CdromToc::TrackType::AudioPCM ||
> 	m_currentTrack->trackType == CdromToc::TrackType::AudioWav)  && (!m_file->isChd())) {
>         int i;
> 	uint16_t *buffer16 = (uint16_t *) buffer;
> 	for (i = 0; i < size / 2; i++) {
> 	  buffer16[i] = BYTE_SWAP_16(buffer16[i]);
> 	}
>     }
> #endif
> ```
> 
> I will look into that once I am back home.

Your fix worked like a charm on the game I tried :) CHD Audio = working! :)

**Comment by rtissera** [comment]
@Ploggy can you make a PR on this repo  to close the issue ?

**Comment by Ploggy** [comment]
> @Ploggy can you make a PR on this repo to close the issue ?

Umm, I'm not sure how to make a PR, I'm not very good at this :P

**Comment by Ploggy** [comment]
I can try :)

**Comment by Ploggy** [comment]
I think this is right? 

https://github.com/libretro/neocd_libretro/pull/93

**Comment by rtissera** [comment]
Looks good but am on phone

**Comment by Ploggy** [comment]
OK thanks. My first PR yay lol I'll close this issue then, thank you guys for your help :)
WiiU AND Wii users appreciate it. :)
